"""Generates the shared UI parts from ui-shared/ into both pages, between marker comments.

    python tools/sync_ui.py            # rewrite the generated blocks in both pages
    python tools/sync_ui.py --check    # exit 1 if a page differs from what the sources generate

Sources: ui-shared/tokens.css (palette; its `@dark { ... }` becomes a prefers-color-scheme media query on Windows and a
`.dark` class rule on Android), ui-shared/components.css, ui-shared/common.js. Output is inline in each page, so
packaging does not change. Edit ui-shared/, never the blocks in the pages.
"""
import argparse
import os
import re
import sys

PAGES = {
    "windows": os.path.join("windows", "ui", "index.html"),
    "android": os.path.join("android", "assets", "index.html"),
}
NOTE = "generated by tools/sync_ui.py from ui-shared/: edit there, not here"
DARK = re.compile(r"@dark\s*\{([^}]*)\}")


def read_lf(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def tokens_for(target, text):
    if target == "windows":
        repl = lambda m: "@media (prefers-color-scheme: dark) {\n  :root {" + m.group(1).replace("\n", "\n  ") + "}\n}"
    else:
        repl = lambda m: ".dark {" + m.group(1) + "}"
    return DARK.sub(repl, text)


def blocks(root, target):
    src = lambda name: read_lf(os.path.join(root, "ui-shared", name)).strip("\n")
    css = tokens_for(target, src("tokens.css")) + "\n" + src("components.css")
    return {
        "css": f"/* ui-shared:css begin ({NOTE}) */\n{css}\n/* ui-shared:css end */",
        "js": f"// ui-shared:js begin ({NOTE})\n{src('common.js')}\n// ui-shared:js end",
    }


def block_re(kind):
    comment = (r"/\* ui-shared:css begin.*?ui-shared:css end \*/" if kind == "css"
               else r"// ui-shared:js begin.*?// ui-shared:js end")
    return re.compile(comment, re.S)


def render(root, target, page_text):
    """page_text with LF endings; returns it with both generated blocks replaced."""
    for kind, block in blocks(root, target).items():
        pattern = block_re(kind)
        if len(pattern.findall(page_text)) != 1:
            raise SystemExit(f"{target}: expected exactly one ui-shared:{kind} block in {PAGES[target]}")
        page_text = pattern.sub(lambda m: block, page_text)
    return page_text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="verify only, change nothing")
    ap.add_argument("--root", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    args = ap.parse_args(argv)
    bad = []
    for target, rel in PAGES.items():
        path = os.path.join(args.root, rel)
        with open(path, encoding="utf-8", newline="") as f:
            raw = f.read()
        crlf = "\r\n" in raw
        want = render(args.root, target, raw.replace("\r\n", "\n"))
        want_raw = want.replace("\n", "\r\n") if crlf else want
        if want_raw == raw:
            continue
        if args.check:
            bad.append(target)
        else:
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(want_raw)
            print(f"updated {rel}")
    if bad:
        print("out of date: " + ", ".join(bad) + ". Run: python tools/sync_ui.py", file=sys.stderr)
        return 1
    if args.check:
        print("ui-shared OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
